version: '3'

services:
  app:
    build:
      context: .
    container_name: micro-videos-elixir-app
    command: /bin/sh docker_dev_start.sh
    volumes:
      - .:/home/elixir/app
    ports:
      - "8000:8000"
    depends_on:
      - db 
    links:
      - db
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5000:5432"